version: '3.8'

services:
  product-microservice:
    build: .
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=powergrid@2?.net
      - DB_NAME=product_microservice
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=powergrid@2?.net
      - POSTGRES_DB=product_microservice
    ports:
      - "5432:5432"
